parts_data = [
    {
        "part_type": "CPU",
        "manufacturer": "AMD",
        "name": "Ryzen 7",
        "speed": 5000,
        "cores": 16,
        "price": 800,
    },
    {
        "part_type": "CPU",
        "manufacturer": "AMD",
        "name": "Ryzen 9",
        "speed": 6000,
        "cores": 32,
        "price": 1600,
    },
    {
        "part_type": "CPU",
        "manufacturer": "AMD",
        "name": "Ryzen 5",
        "speed": 4500,
        "cores": 12,
        "price": 500,
    },
    {
        "part_type": "CPU",
        "manufacturer": "AMD",
        "name": "Ryzen 3",
        "speed": 4000,
        "cores": 8,
        "price": 300,
    },
    {
        "part_type": "CPU",
        "manufacturer": "Intel",
        "name": "Core i-3",
        "speed": 4000,
        "cores": 8,
        "price": 300,
    },
    {
        "part_type": "CPU",
        "manufacturer": "Intel",
        "name": "Core i-9",
        "speed": 5000,
        "cores": 32,
        "price": 1500,
    },
    {
        "part_type": "CPU",
        "manufacturer": "AMD",
        "name": "Ryzen 3",
        "speed": 4000,
        "cores": 8,
        "price": 300,
    },
    {
        "part_type": "CPU Cooler",
        "manufacturer": "Be quiet",
        "name": "Quiet",
        "color": "black",
        "price": 100,
    },
    {
        "part_type": "Motherboard",
        "manufacturer": "Asus",
        "name": "Gaming",
        "processor type": "AMD",
        "price": 300,
    },
    {
        "part_type": "Memory",
        "manufacturer": "Crucial",
        "name": "Ripjaws",
        "speed": 4000,
        "size": 32,
        "price": 100,
    },
    {
        "part_type": "Storage",
        "manufacturer": "Samsung",
        "name": "980 Pro",
        "storage type": "nvme",
        "capacity": 2,
        "price": 100,
    },
    {
        "part_type": "Video Card",
        "manufacturer": "Gigabyte",
        "name": "RTX 3080",
        "color": "black",
        "price": 800,
    },
    {
        "part_type": "Case",
        "manufacturer": "Corsair",
        "name": "4000D",
        "color": "black",
        "price": 100,
    },
    {
        "part_type": "PSU",
        "manufacturer": "Corsair",
        "name": "RM1000x",
        "color": "black",
        "power": 1000,
        "price": 200,
    },
    {
        "part_type": "Monitor",
        "manufacturer": "Asus",
        "name": "TUF GAMING",
        "color": "black",
        "size": 27,
        "price": 800,
    },
]
